apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-fail.fullname" . }}
  labels:
    {{- include "go-fail.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-fail.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-fail.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ add .Values.config.startupTime 5 }}
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.config.startupTime }}
            periodSeconds: 5
          env:
            - name: STARTUP_TIME
              value: "{{ .Values.config.startupTime }}"
            - name: TIME_BEFORE_EXIT
              value: "{{ .Values.config.timeBeforeExit }}"
            - name: EXIT_CODE
              value: "{{ .Values.config.exitCode }}"
            - name: PORT
              value: "{{ .Values.config.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}