on:
  repository_dispatch:
    types: [argocd-deployment]

jobs:
  handle-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Use payload data
      run: |
        echo "Application: ${{ github.event.client_payload.application }}"
        echo "Revision: ${{ github.event.client_payload.revision }}"
        echo "Health: ${{ github.event.client_payload.health_status }}"
